services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - es
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  esdata:
  node_modules:
