services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - redis
    env_file: .env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    networks:
      - app-network
  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  redis_data:
